Update readme files
RockLib/RockLib.Configuration pull request #29
Opened 2018-03-20 16:51 UTC by bfriesen

- Create separate readme files for each package.
- Update main readme to link to each package.
- Remove old content from main readme.

2018-03-20 16:54 UTC, derikwhittaker commented
I like the build status.  Smart on breaking into smaller files

2018-03-20 17:26 UTC, JustinMoss requested changes
Overall great.  Found a few typos I think though.

2018-03-20 17:26 UTC, JustinMoss commented on README.md
> +An alternative to `Microsoft.Extensions.Configuration.Binder` that supports readonly properties and other features commonly found in JSON and XML serializers.
This line does not exactly match the summary for the RockLib.Configuration.ObjectFactory.  Though it's not wrong, it's not consistent with the other two packages summaries.

2018-03-20 17:26 UTC, JustinMoss commented on RockLib.Configuration.ObjectFactory/README.md
> +a instance of `Foo` can be created with a `Baz` property with a value of type `BazDerived` by specifying a `type/value` pair where the `type` is a *[assembly quallified name](https://msdn.microsoft.c
[assembly quallified name] should be [assembly qualified name]

2018-03-20 17:26 UTC, JustinMoss commented on RockLib.Configuration.ObjectFactory/README.md
> +We would like to be able to define the `DefaultBar` type as the default type - if the type is not otherwise specified, create an instance of `DefaultBar`. There are two ways of specifying the default
Should this close off the code section?  It seems to look funny here in the readme

2018-03-20 17:26 UTC, JustinMoss commented on RockLib.Configuration.ObjectFactory/README.md
> +RockLib converts most configuration string values to the target type by using the `TypeConverter` obtained by calling `TypeDescriptor.GetConverter(targetType)`. In addition, there is support for targ
"These value converters a functions" should be "These value converters are functions"

2018-03-21 14:45 UTC, JustinMoss approved these changes

2018-03-21 14:48 UTC, merged